# Build lflags.rda file from flag SVGs

# apt install libcairo2-dev libspectre-dev librsvg2-dev libpoppler-glib-dev r-base-dev
# devtools::install_github("sjp/grConvert")
library(grConvert)
library(grImport2)

# input svg folder location
input_path_emojione <- "./inst/emojione-flags/"
input_path_extra <- "./inst/extra-flags/"
# output cairo folder location
cairo_path <- "./inst/cairo/"

# Convert emojione-flags ------------------------------------------

# Label flag SVG files with ISO country codes
UnicodeToISOCountryCode <- function (x) {
  paste0(LETTERS[strtoi(x, base = 16)-strtoi(0x1F1A5)-64], collapse = '')
}

filenames_old <- list.files(input_path_emojione, pattern = glob2rx("*.svg"))

filenames_new <- sapply(
  strsplit(gsub('.svg', '', filenames_old), split = '-'),
  function (x) {
    paste0(UnicodeToISOCountryCode(x), '.svg')
  }
)

# grImport2 requires an SVG image that has been generated by the Cairo
# graphics library here we ensure that this is the case by converting
# existing SVGs
for (i in 1:length(filenames_old)) {
  convertPicture(paste0(input_path_emojione, filenames_old[i]),
                 paste0(cairo_path, filenames_new[i]))
}

# Convert extra-flags ---------------------------------------------

filenames_old <- list.files(input_path_extra, pattern = glob2rx("*.svg"))
filenames_new <- filenames_old

for (i in 1:length(filenames_old)) {
  convertPicture(paste0(input_path_extra, filenames_old[i]),
                 paste0(cairo_path, filenames_new[i]))
}

# Create RDS file -------------------------------------------------

lf <- list.files(path = cairo_path, pattern = glob2rx("*.svg"),
                 full.names = TRUE)

lflags <- lapply(lf, readPicture)
names(lflags) <- tolower(gsub("^.+cairo//|\\.svg", "", lf))

# Export ----------------------------------------------------------

save(lflags, file="./data/lflags.rda", compress = 'xz')
